version: "3"

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static/build:/opt/dashboard
    networks:
      - nginx_network
    depends_on:
      - server

  server:
    working_dir: /opt/services/webapp
    env_file:
      - config/.env
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/opt/services/webapp
      # - static_volume:/opt/static  # <-- bind the static volume
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - database1

  database1:
    image: postgres:10
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  database1_volume:
  static_volume: