# start from an official image
FROM python:3.7

# Configure apt
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get -y install --no-install-recommends apt-utils 2>&1

# Install git, process tools, lsb-release (common in install instructions for CLIs)
RUN apt-get -y install git procps lsb-release

# Install any missing dependencies for enhanced language service
RUN apt-get install -y libicu[0-9][0-9]

# Install Node
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install nodejs && node -v && npm -v

# Clean up
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=dialog

# arbitrary location choice: you can change the directory
RUN mkdir -p /opt/services/webapp
WORKDIR /opt/services/webapp

# copy our project code
COPY ./*.txt /opt/services/webapp/

# install our two dependencies
RUN pip install -r requirements-dev.txt --upgrade --no-warn-script-location
RUN npm install --prefix ./static

# Set the default shell to bash rather than sh
ENV SHELL /bin/bash